version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: moon_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_ROOT_PASSWORD: super_secret_root_pass
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: moon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: ./ 
    container_name: moon_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DATABASE_URL: ${SQL_USER}:${SQL_PASSWORD}@tcp(db:3306)/${SQL_DB}?parseTime=true
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"

volumes:
  mysqldata: